### ISSUE TITLE
open office downloads file instead of opening

### ISSUE THREAD

**Issue by johnbangad** [ONLYOFFICE/docker-onlyoffice-owncloud#21] opened 2018-07-31 10:28 UTC
![image](https://user-images.githubusercontent.com/38520023/43454421-2b7ff45e-94e7-11e8-8bdc-c60cdff115e2.png)

**Comment by HelenBelova17** [comment] 2018-07-31 13:40
Hello, **@johnbangad**, please specify some additional information about the issue:

1. Which version of Nextcloud and Document Server are you using?
2. Describe steps by steps your doing.
3. Be sure Document Server is enabled before open the file.
4. Send us a screenshot of Onlyoffice settings.

**Comment by johnbangad** [comment] 2018-08-01 02:07
1. nextcloud is 13.0.4 and document server is 1.3
2. only office was suddenly cut off from next cloud then this happens. 
3. Only office is enabled in apps
4. here is the screen shot of the settings
![image](https://user-images.githubusercontent.com/38520023/43496723-1bbf1072-9569-11e8-8633-64d22eab8d11.png)


ps. Onlyoffice and nextcloud is working fine again today.

**Comment by HelenBelova17** [comment] 2018-08-03 12:19
**@johnbangad**, as far as we understood, the issue is resolved at the moment, can we close it?

**Comment by johnbangad** [comment] 2018-08-06 01:07
Yes please, maybe it was in our end. server issues. Thanks again! :)

**Closed** 2018-08-06 07:13 UTC
